"""add wallets and credit_ledger tables

Revision ID: 4b4c15a9e70c
Revises: '4c274da07554'
Create Date: 2026-09-05 23:55:14.131860

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b4c15a9e70c"
down_revision: str | None = "4c274da07554"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("cached_balance", sa.Integer(), nullable=False),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("ix_wallets_user_id", "wallets", ["user_id"], unique=True)
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "TOPUP",
                "SPEND",
                "PROMO",
                "REFUND",
                "TIP",
                name="transactiontype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("reference_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_credit_ledger_idempotency_key",
        "credit_ledger",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        "ix_credit_ledger_user_id", "credit_ledger", ["user_id"], unique=False
    )
    op.create_index(
        "ix_credit_ledger_wallet_id", "credit_ledger", ["wallet_id"], unique=False
    )

    # Enterprise Security: DB Trigger blocking UPDATE and DELETE on credit_ledger
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_credit_ledger_modification()
    RETURNS TRIGGER AS $$
    BEGIN
        RAISE EXCEPTION 'credit_ledger table is append-only. '
                        'UPDATE and DELETE operations are strictly forbidden.';
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trigger_prevent_credit_ledger_update_delete
    BEFORE UPDATE OR DELETE ON credit_ledger
    FOR EACH ROW
    EXECUTE FUNCTION prevent_credit_ledger_modification();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS trigger_prevent_credit_ledger_update_delete "
        "ON credit_ledger;"
    )
    op.execute("DROP FUNCTION IF EXISTS prevent_credit_ledger_modification();")
    op.drop_index("ix_credit_ledger_wallet_id", table_name="credit_ledger")
    op.drop_index("ix_credit_ledger_user_id", table_name="credit_ledger")
    op.drop_index("ix_credit_ledger_idempotency_key", table_name="credit_ledger")
    op.drop_table("credit_ledger")
    op.drop_index("ix_wallets_user_id", table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
